### ISSUE TITLE
1.7.x Plugin Dev Issues

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/Master#794]
This is a tracking issue to log the issues under dev and closed that are managed on the actually code repo (https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin)

The issues there are mainly for the Dev Team and don't require direct QA involvement
- [ ] [Add better 'TM Eclipse Add-in' capabilities](https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/26)
- [ ] [Split Fortify specific code into its own repo](https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/27)
- [ ] [Improve Goovy Editor](https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/28)

These are the normal 'Tracking issues' (i.e. issues that issues on both repor)
- [Keep statistics on missing content](https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/11)
- [Add editor for Fortify to TM Mappings](https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/4)
