### ISSUE TITLE
As a customer I should be able to configure TM such that I can control how accounts are created

### ISSUE THREAD

**Issue by romichg** [TeamMentor/Master#883]
- [ ] #495 It should be possible to configure TeamMentor to disallow signup, and only display login link
- [ ] Users are allowed to sign up, but need to be approved by an administrator ( #763 )
- [ ] Users are allowed to sign up for a period of time before they expire
- [ ] Users are allowed to sign up indefinitely
  - [ ] If users are allowed to sign up -  #183 Should Login after Account Creation
  - [ ] If users are allowed to sign up - #373 
- [ ] Users can SSO in from other systems and do not need to sign up
- [ ] Users do not need to sign up as content is anonymous
- [ ] Users are integrated with Active directory
- [ ] Customers should be able to disable the default landing pages / replace them with their own (https://github.com/TeamMentor/TM_4_0_Design/issues/51)
