### ISSUE TITLE
As a user, after searching, I should be able to select a set of filters, which are presented in an intuitive and aesthetically pleasing  way, such that my available set of articles is narrowed down by the filters

### ISSUE THREAD

**Issue by romichg** [TeamMentor/Master#899]
- [ ] Each filter should have a set of parameters that are ether ORed or ANDed together based on what the filter is. The operation should be visually intuitive (checkboxes vs radio buttons) (related to #118)
- [ ] The resulting set of all the filters should be ANDed together
- [ ] Each filter should display a count of articles next to it that match THAT filter. The count should update if other GROUP of filters are selected already and would reduce the total article count if that filter was selected by itself.
- [ ] Technology agnostic articles should be represented by "AGNOSTIC" label as opposed to "ANY" label  ( #49 #113  )
- [ ] No filters should be grayed out. Instead article count next to the filters should be updated (as explained above) #324 
- [ ] Once all the filters are selected, total article result set count should be displayed  ( Related to #207)
- [ ] Once selected filters should remain selected and applied to all the searches and/or navigation until explicitly removed. The process should be intuitive (Related to #613 #115 #326, #329, #528, #529 )  
- [ ] #117 
- [ ] #612

**Comment by roman87** [comment]
Moving this to sprint 3 as we will not have all of this done by release.
